"""user-subscriptions2

Revision ID: 3ea28ea466cc
Revises: a27bf7cee683
Create Date: 2025-06-10 12:59:14.590099

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ea28ea466cc'
down_revision: Union[str, None] = 'a27bf7cee683'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('subscribers_count', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'subscribers_count')
    # ### end Alembic commands ###
