"""upload-date-views

Revision ID: 69f7913d53a7
Revises: abe324179478
Create Date: 2025-06-18 11:43:29.265462

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69f7913d53a7'
down_revision: Union[str, None] = 'abe324179478'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('upload_date', sa.DateTime(), nullable=True))
    op.add_column('videos', sa.Column('views', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'views')
    op.drop_column('videos', 'upload_date')
    # ### end Alembic commands ###
