"""comments

Revision ID: f7d197e0552b
Revises: 30f8ad75c00f
Create Date: 2025-06-03 12:01:13.415562

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7d197e0552b'
down_revision: Union[str, None] = '30f8ad75c00f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('likes', sa.Integer(), nullable=True),
    sa.Column('dislikes', sa.Integer(), nullable=True),
    sa.Column('creator_like', sa.Boolean(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('video_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comments_creator_like'), 'comments', ['creator_like'], unique=False)
    op.create_index(op.f('ix_comments_date'), 'comments', ['date'], unique=False)
    op.create_index(op.f('ix_comments_dislikes'), 'comments', ['dislikes'], unique=False)
    op.create_index(op.f('ix_comments_id'), 'comments', ['id'], unique=False)
    op.create_index(op.f('ix_comments_likes'), 'comments', ['likes'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_comments_likes'), table_name='comments')
    op.drop_index(op.f('ix_comments_id'), table_name='comments')
    op.drop_index(op.f('ix_comments_dislikes'), table_name='comments')
    op.drop_index(op.f('ix_comments_date'), table_name='comments')
    op.drop_index(op.f('ix_comments_creator_like'), table_name='comments')
    op.drop_table('comments')
    # ### end Alembic commands ###
